export default [
   {
      "id":110,
      "movieName":"알라딘(재개봉)",
      "startDate":"2019년 5월 23일",
      "openingDate" : "2019년 5월 23일",
      "advanceRate" : "개봉전",
      "grade" : "★★★★★",
      "mPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_m_aladdin.jpg?raw=true",
      "wPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_w_aladdin.jpg?raw=true",
      "intro":"1992년에 개봉한 디즈니 애니메이션 알라딘을 원작으로 하는 실사 영화",
      "synop":"머나먼 사막 속 신비의 아그라바 왕국의 시대. 좀도둑 ‘알라딘’은 마법사 ‘자파’의 의뢰로 마법 램프를 찾아 나섰다가 주인에게 세 가지 소원을 들어주는 지니를 만나게 되고, 자스민 공주의 마음을 얻으려다 생각도 못했던 모험에 휘말리게 되는데…",
      "rank":2,
      "director":"가이 리치",
      "actor":[
         {"name":"미나 마수드","number":"480843","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_aladdin1.png?raw=true"},         
         {"name":"나오미 스콧","number":"267584","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_aladdin2.png?raw=true"},
         {"name":"윌 스미스","number":"664","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_aladdin3.png?raw=true"},
      ],
      "genre":"판타지, 뮤지컬, 로맨틱 코미디, 모험",
      "watchGradeNm":"전체 관람가",
      "runningTime" : "128분",
      "repNationCd" : "미국" ,
      "youtube" : "https://www.youtube.com/watch?v=9g5knnlF7Zo"
   },
   {
      "id":1,
      "movieName":"탑건-매버릭",
      "startDate":"2022년 6월 22일",
      "openingDate" : "2022년 4월 28일",
      "advanceRate" : "9.05",
      "grade" : "★★★★★",
      "mPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_m_topgun.jpg?raw=true",
      "wPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_w_topgun.jpg?raw=true",
      "intro":"한순간의 실수도 용납되지 않는 하늘 위, 가장 압도적인 비행이 시작된다!",
      "synop":"최고의 파일럿이자 전설적인 인물 매버릭(톰 크루즈)은 자신이 졸업한 훈련학교 교관으로 발탁된다.그의 명성을 모르던 팀원들은 매버릭의 지시를 무시하지만 실전을 방불케 하는 상공 훈련에서 눈으로 봐도 믿기 힘든 전설적인 조종 실력에 모두가 압도된다. 매버릭의 지휘아래 견고한 팀워크를 쌓아가던 팀원들에게 국경을 뛰어넘는 위험한 임무가 주어지자매버릭은 자신이 가르친 동료들과 함께 마지막이 될 지 모를 하늘 위 비행에 나서는데… ",
      "rank":3,
      "director":"조지프 코신스키",
      "actor":[
         {"name":"톰 크루즈","number":"492","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_topgun1.png?raw=true"},         
         {"name":"마일스 텔러","number":"185250","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_topgun2.png?raw=true"},
         {"name":"제니퍼 코넬리","number":"778","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_topgun3.png?raw=true"},
      ],
      "genre":"액션",
      "watchGradeNm":"12세 관람가",
      "runningTime" : "131분",
      "repNationCd" : "미국" ,      
      "youtube" : "https://www.youtube.com/watch?v=Mrj9XACVJ8U"
   },
   {
      "id":2,
      "movieName":"한산 : 용의 출현",
      "startDate":"2022년 7월 27일",
      "openingDate" : "2022년 7월 27일",
      "advanceRate" : "7.88",
      "grade" : "★★★",
      "mPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_m_hansan.jpg?raw=true",
      "wPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_w_hansan.jpg?raw=true",
      "intro":"나라의 운명을 바꿀 압도적 승리의 전투가 시작된다!",
      "synop":"1592년 4월, 조선은 임진왜란 발발 후 단 15일만에 왜군에 한양을 빼앗기며 절체절명의 위기에 놓인다. 조선을 단숨에 점령한 왜군은 명나라로 향하는 야망을 꿈꾸며 대규모 병역을 부산포로 집결시킨다. 한편, 이순신 장군은 연이은 전쟁의 패배와 선조마저 의주로 파천하며 수세에 몰린 상황에서도 조선을 구하기 위해 전술을 고민하며 출전을 준비한다. 하지만 앞선 전투에서 손상을 입은 거북선의 출정이 어려워지고, 거북선의 도면마저 왜군의 첩보에 의해 도난 당하게 되는데… 왜군은 연승에 힘입어 그 우세로 한산도 앞바다로 향하고, 이순신 장군은 조선의 운명을 가를 전투를 위해 필사의 전략을 준비한다. 1592년 여름, 음력 7월 8일 한산도 앞바다, 압도적인 승리가 필요한 조선의 운명을 건 지상 최고의 해전이 펼쳐진다.",
      "rank":9,
      "director":"김한민",
      "actor":[
         {"name":"박해일","number":"1316","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_hansan1.png?raw=true"},         
         {"name":"변요한","number":"261949","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_hansan2.png?raw=true"},
         {"name":"안성기","number":"546","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_hansan3.png?raw=true"},
      ],
      "genre":"액션, 드라마",
      "watchGradeNm":"12세 관람가",
      "runningTime" : "130분",
      "repNationCd" : "대한민국"  ,      
      "youtube" : "https://www.youtube.com/watch?v=FLNUcZxCT6k"
   },
   {
      "id":3,
      "movieName":"라라랜드",
      "startDate":"2016년 12월 7일",
      "openingDate" : "2016년 12월 8일",
      "advanceRate" : "9.89",
      "grade" : "★★★★★",
      "mPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_m_lalaland.jpg?raw=true",
      "wPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_w_lalaland.jpg?raw=true",
      "intro":"황홀한 사랑, 순수한 희망, 격렬한 열정… 이 곳에서 모든 감정이 폭발한다!",
      "synop":"꿈을 꾸는 사람들을 위한 별들의 도시 ‘라라랜드’. 재즈 피아니스트 ‘세바스찬’(라이언 고슬링)과 배우 지망생 ‘미아’(엠마 스톤), 인생에서 가장 빛나는 순간 만난 두 사람은 미완성인 서로의 무대를 만들어가기 시작한다.",
      "rank":1,
      "director":"데이미언 셔젤",
      "actor":[
         {"name":"라이언 고슬링","number":"8129","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_lalaland1.png?raw=true"},         
         {"name":"엠마스톤","number":"124100","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_lalaland2.png?raw=true"}
      ],
      "genre":"드라마, 뮤지컬, 로맨스, 멜로",
      "watchGradeNm":"12세 관람가",
      "runningTime" : "127분",
      "repNationCd" : "미국"  ,      
      "youtube" : "https://www.youtube.com/watch?v=o8oZ-qOmgtc"
   },
   {
      "id":4,
      "movieName":"그래비티",
      "startDate":"2013년 10월 4일",
      "openingDate" : "2013년 10월 17일",
      "advanceRate" : "6.96",
      "grade" : "★★★",
      "mPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_m_gravity.jpg?raw=true",
      "wPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_w_gravity.jpg?raw=true",
      "intro":"외계인도, 우주전쟁도 없다. 이것이. 누구도 경험하지 못한 진짜 재난이다.",
      "synop":"허블 우주망원경을 수리하기 위해 우주를 탐사하던 라이언 스톤 박사는 폭파된 인공위성의 잔해와 부딪히면서 소리도 산소도 없는 우주 한 가운데에 홀로 남겨지는데…",
      "rank":10,
      "director":"알폰소 쿠아론",
      "actor":[
         {"name":"산드라 블록","number":"665","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_gravity1.png?raw=true"},         
         {"name":"조지 클루니","number":"525","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_gravity2.png?raw=true"}
      ],
      "genre":"스릴러, 재난, 생존, SF",
      "watchGradeNm":"12세 관람가",
      "runningTime" : "91분",
      "repNationCd" : "미국"  ,      
      "youtube" : "https://www.youtube.com/watch?v=ql8WbM3Qea8"
   },
   {
      "id":5,
      "movieName":"이프 온리",
      "startDate":"2004년 10월 29일",
      "openingDate" : "2004년 10월 29일",
      "advanceRate" : "7.8",
      "grade" : "★★★★",
      "mPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_m_ifOnly.jpg?raw=true",
      "wPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_w_ifOnly.jpg?raw=true",
      "intro":"오늘, 비로소 사랑을 알았어",
      "synop":"눈앞에서 사랑하는 연인을 잃은 남자는 다음 날 아침, 자신의 옆에서 자고 있는 연인을 보고 소스라치게 놀란다. 기쁨도 잠시, 정해진 운명은 바꿀 수 없단 것을 깨달은 그는 더 늦기 전에 자신의 진정한 사랑을 전하기로 마음먹는데…",
      "rank":7,
      "director":"길 정거",
      "actor":[
         {"name":"제니퍼 러브 휴이트","number":"552","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_ifOnly1.png?raw=true"},         
         {"name":"폴 니콜스","number":"93699","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_ifOnly2.png?raw=true"},
      ],
      "genre":"로맨틱 코미디, 멜로",
      "watchGradeNm":"15세 이상",
      "runningTime" : "96분",
      "repNationCd" : "영국,미국" ,
      "youtube" : "https://www.youtube.com/watch?v=40Ahmsbae94"
   },
   {
      "id":6,
      "movieName":"업(Up)",
      "startDate":"2009년 7월 29일",
      "openingDate" : "2009년 7월 29일",
      "advanceRate" : "8.12",
      "grade" : "★★★★",
      "mPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_m_up.jpg?raw=true",
      "wPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_w_up.jpg?raw=true",
      "intro":"한방울 눈물과 한바탕 웃음! 2009년 가장 아름다운 영화 <업>",
      "synop":"성격 까칠한 할아버지 ‘칼’과 귀여운 8살 탐험가 ‘러셀’이 만났다! 평생 모험을 꿈꿔 왔던 ‘칼’ 할아버지는 수천 개의 풍선을 매달아 집을 통째로 남아메리카로 날려 버리는데, ‘칼’ 할아버지의 이 위대한 모험에 초대 받지 않은 불청객이 있었으니, 바로 황야의 탐험가 ‘러셀’! 지구상에 둘도 없을 이 어색한 커플이 함께 하는 대모험. 그들은 과연 남미의 잃어버린 세계에서 사라져 버린 꿈과 희망,행복을 다시 찾을 수 있을까?",
      "rank":6,
      "director":"피트 닥터, 밥 피터슨",
      "actor":[
         {"name":"에드워드 애스너","number":"12952","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_up1.png?raw=true"},         
         {"name":"크리스토퍼 플러머","number":"1505","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_up2.png?raw=true"},
      ],
      "genre":"어드벤처, 애니메이션",
      "watchGradeNm":"전체 관람가",
      "runningTime" : "101분",
      "repNationCd" : "미국" ,      
      "youtube" : "https://www.youtube.com/watch?v=6J6ADorSeYc"
   },
   {
      "id":7,
      "movieName":"반지의 제왕",
      "startDate":"2001년 12월 31일",
      "openingDate" : "2001년 12월 31일",
      "advanceRate" : "9.0",
      "grade" : "★★★★★",
      "mPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_m_ring.jpg?raw=true",
      "wPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_w_ring.jpg?raw=true",
      "intro":"21세기 가장 위대한 판타지 걸작의 귀환! <반지의 제왕> 시리즈 확장판 스크린 최초개봉!",
      "synop":"모든 힘을 지배할 악의 군주 ‘사우론’의 절대반지가 깨어나고 악의 세력이 세상을 지배해가며 중간계는 대혼란에 처한다. 호빗 ‘프로도’와 그의 친구들, 엘프 ‘레골라스’, 인간 전사 ‘아라곤’과 ‘보로미르’ 드워프 ‘김리’ 그리고 마법사 ‘간달프’로 구성된 반지원정대는 평화를 지키기 위해 절대반지를 파괴할 유일한 방법인 반지가 만들어진 모르도르를 향해 목숨을 건 여정을 떠난다. 한편, 점점 세력을 넓혀온 사우론과의 피할 수 없는 전쟁을 앞둔 반지원정대는 드디어 거대한 최후의 전쟁을 시작하는데...",
      "rank":4,
      "director":"피터 잭슨",
      "actor":[
         {"name":"일라이저 우드","number":"2440","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_ring1.png?raw=true"},         
         {"name":"이안 맥켈런","number":"2482","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_ring2.png?raw=true"},
         {"name":"리브 타일러","number":"8655","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_ring3.png?raw=true"},
      ],
      "genre":"판타지, 어드벤처",
      "watchGradeNm":"12세 관람가",
      "runningTime" : "165분",
      "repNationCd" : "뉴질랜드, 미국",      
      "youtube" : "https://www.youtube.com/watch?v=CGLblhh6RTA"
   },
   {
      "id":8,
      "movieName":"부산행",
      "startDate":"2016년 07월20일",
      "openingDate" : "2016년 07월20일",
      "advanceRate" : "7.2",
      "grade" : "★★★",
      "mPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_m_busan.jpg?raw=true",
      "wPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_w_busan.jpg?raw=true",
      "intro":"전대미문의 재난이 대한민국을 덮친다!",
      "synop":"정체불명의 바이러스가 전국으로 확산되고 대한민국 긴급재난경보령이 선포된 가운데, 열차에 몸을 실은 사람들은 단 하나의 안전한 도시 부산까지 살아가기 위한 치열한 사투를 벌이게 된다.",
      "rank":8,
      "director":"연상호",
      "actor":[
         {"name":"공유","number":"5493","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_busan1.png?raw=true"},         
         {"name":"정유미","number":"96817","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_busan2.png?raw=true"},         
         {"name":"김수안","number":"265593","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_busan3.png?raw=true"}
      ],
      "genre":"액션, 스릴러",
      "watchGradeNm":"15세 관람가",
      "runningTime" : "118분",
      "repNationCd" : "대한민국"  ,      
      "youtube" : "https://www.youtube.com/watch?v=UOTOjA0ngmk"
   },
   {
      "id":9,
      "movieName":"어벤져스:엔드게임",
      "startDate":"2019년 04월 24일",
      "openingDate" : "2019년 04월 24일",
      "advanceRate" : "8.25",
      "grade" : "★★★★",
      "mPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_m_endgame.jpg?raw=true",
      "wPoster":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/poster_w_endgame.jpg?raw=true",
      "intro":"위대한 어벤져스, 운명을 바꿀 최후의 전쟁이 펼쳐진다!",
      "synop":"인피니티 워 이후 절반만 살아남은 지구, 마지막 희망이 된 어벤져스 먼저 떠난 그들을 위해 모든 것을 걸었다!",
      "rank":5,
      "director":"앤서니 루소, 조 루소",
      "actor":[
         {"name":"로버트 다우니 주니어","number":"8357","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_endgame1.png?raw=true"},         
         {"name":"크리스 에반스","number":"43624","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_endgame2.png?raw=true"},         
         {"name":"마크 러팔로","number":"9144","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_endgame3.png?raw=true"},         
         {"name":"스칼렛 요한슨","number":"11739","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_endgame4.png?raw=true"},         
         {"name":"제레미 레너","number":"96681","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_endgame5.png?raw=true"},         
         {"name":"폴 러드","number":"19931","img":"https://github.com/ssunakimm/ssunakimm.github.io/blob/main/port/vue/movie/img/actor_endgame6.png?raw=true"}
      ],
      "genre":"액션, SF",
      "watchGradeNm":"12세 관람가",
      "runningTime" : "191분",
      "repNationCd" : "미국"  ,      
      "youtube" : "https://www.youtube.com/watch?v=Ko2NWhXI9e8"
   }
 ]
